apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: develop-panic-button-app-{{PR_NUMBER}}
  name: develop-panic-button-app-{{PR_NUMBER}}
  namespace: panic-pr-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: develop-panic-button-app-{{PR_NUMBER}}
  template:
    metadata:
      labels:
        app: develop-panic-button-app-{{PR_NUMBER}}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-panic-button-app: 'internal/data/panic-button-app'
        vault.hashicorp.com/agent-inject-template-panic-button-app: |
          {{- with secret "internal/data/panic-button-app" -}}
            {{- range $key, $value := .Data.data }}
              export {{ $key }}={{ $value }}
            {{- end }}
          {{- end -}}
    spec:
      containers:
      - name: develop-panic-button-app-{{PR_NUMBER}}
        image: registry.digitalocean.com/karpatkey/panic-button-app:pr{{DOCKER_TAG}}
        imagePullPolicy: Always
        command:
          ['/bin/sh', '-c']
        args:
          ['source /vault/secrets/panic-button-app && yarn dev']
        ports:
        - containerPort: 3000
          protocol: TCP
        env: 
        - name: AUTH0_BASE_URL
          value: "{{PR_SUBDOMAIN}}"

        - name: DATA_WAREHOUSE_ENV
          value: development

        - name: MODE
          value: development

        - name: LOCAL_FORK_PORT_ETHEREUM
          value: "8546"
          
        - name: LOCAL_FORK_PORT_GNOSIS
          value: "8547"
        
         # LOCAL_FORK_HOST = anvil
      
      
      - name: ethereum
        image: ghcr.io/foundry-rs/foundry:latest
        imagePullPolicy: Always
        
        command:
          - 'anvil'
        args:
          - '--accounts'
          - '15'
          - '-f'
          - 'https://rpc.mevblocker.io'
          - '--port'
          - '8546'
          - '--host'
          - '0.0.0.0'
        
        ports:
        - containerPort: 8546
          protocol: TCP

      - name: gnosis
        image: ghcr.io/foundry-rs/foundry:latest
        imagePullPolicy: Always

        command:
          - 'anvil'
        args:
          - '--accounts'
          - '15'
          - '-f'
          - 'https://rpc.gnosischain.com/'
          - '--port'
          - '8547'
          - '--host'
          - '0.0.0.0'
        
        ports:
        - containerPort: 8547
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: develop-panic-button-app-{{PR_NUMBER}}
  namespace: panic-pr-review
spec:
  ports:
  - port: 3000
    name: one
    protocol: TCP
    targetPort: 3000

  selector:
    app: develop-panic-button-app-{{PR_NUMBER}}
  